# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20170610_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
