# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_remove_messages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='chat_app.UserProfile'),
            preserve_default=False,
        ),
    ]
